version: '3'

services:
  app:
    build:
      dockerfile: ops/docker/app/Dockerfile
      context: .
    ports:
      - 80:80
    dns: 8.8.8.8
    volumes:
      - ./:/var/www/html

  db:
    image: couchbase
    ulimits:
      nofile: 40960
      core: 1000000
      memlock: 1000000
    ports:
      - 8091-8097:8091-8097
      - 11210:11210
      - 11207:11207
      - 18091-18095:18091-18095
      - 18096:18096
      - 18097:18097